name: CFSant.Dev.Commons

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.402
    - name: Restore dependencies
      run: dotnet restore ./Commons/Commons/Commons.csproj
    - name: Build
      run: dotnet build --no-restore ./Commons/Commons/Commons.csproj
    - name: Pack
      run: dotnet pack -o ./ ./Commons/Commons/Commons.csproj
    - name: Publish
      run: nuget push ./CFSant.Dev.Commons.1.0.1.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.MAIN}}
